# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c86968dd3ab4f7472d143e9a1c363c9edffc91731ebc2f25bf31aaecff4057f0c0590d3b11ad5d878af4caf63ced9ab54cc2c028c9d7292998c55d0859250e77

test:
  secret_key_base: 048d713c9485379acb1eae124fc14cd178fb2fd8294e4c53e3b9ab0f67157c7be926de563dab7627672f52e5deb1656502ff18855e82441c658bb57edc7801f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
